name: Create Release and Upload Asset

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    # --- 这是我们新增加的关键部分 ---
    permissions:
      contents: write
    # ---------------------------------
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Zip plugin files
        run: |
          # Package the plugin for release: include manifest, provider, tools, assets and generated difypkg if present
          zip -r release.zip manifest.yaml provider tools _assets assets requirements.txt README.md PRIVACY.md LICENSE heygen-dify-plugin.difypkg || \
          # Fallback: if difypkg not present, still create zip without it
          zip -r release.zip manifest.yaml provider tools _assets assets requirements.txt README.md PRIVACY.md LICENSE

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
